### PR TITLE
[Content] Spring 2024 tornado season data story

### PR DESCRIPTION
**Pull request by acblackford**
## Why are you creating this Pull Request?

- [Adding Datasets or Stories](?title=Content%3A%20%3Cname%3E&expand=1&template=content.md)
- [Version Release](?title=Deploy%20vX.X.X&expand=1&template=version_release.md)
- [Other](?expand=1&template=default.md)

### CODE REVIEW

**Comment by aboydnw** [comment]
@acblackford a lot of these images are really large, can you look into compressing them? Ideally each one is <500 kb. Large images will affect our [lighthouse score](https://github.com/NASA-IMPACT/veda-ui/issues/688#issuecomment-2212993137)

**Comment by aboydnw** [comment]
Yeah, any of the stories/tornadoes-2024-* photos look large, multiple MBs

**Comment by acblackford** [comment]
@aboydnw Datasets are not yet fully pushed to production (working on that now), but the content of this story and associated dataset landing pages are ready for a review so that once these datasets are in prod we can include this PR in the next release. This is a big, highly-collaborative story!

**Comment by aboydnw** [comment]
Thanks @acblackford 
At first glance, I'd say we wait to do a review until the datasets are published. One big reason being I think we ever want to change the environment variables to point to staging STAC. I assume you did this because data isn't in prod yet, so once it's in prod then you'll want to update this PR to point to the prod records. Then it'll be ready for review.

**Comment by aboydnw** [comment]
@acblackford I'm going through and testing now, since it's short notice I'll post this comment now before I'm done testing. First thing I notice is that all the datasets could use an `infoDescription`

See the recent PR for NLDAS for an example. #498 My suggestion would be to use the bulleted list of "Dataset Details" that you have in the body of each dataset mdx file already.

**Comment by aboydnw** [comment]
@acblackford the only other thing that I notice is that the email link at the bottom probably is not functioning as intended. It just opens a page with mailto appended at the end of the URL. I actually see recent stories with it, like Black Belt, also behaving this way.

Off the top of my head I'm not sure how to solution this, or if we have encountered this in the past. Do you have any ideas? Maybe for a short term solution we just remove it as a link?

**Comment by acblackford** [comment]
@aboydnw All datasets should now have info descriptions added

**Review by aboydnw — APPROVED** [review]
Looks good to me. Also a really interesting story and data. Nice work. Let's include in the release next week @snmln 

(based on @anayeaye telling me this is ready to go)

**Pull request merged**
