### PR TITLE
Reflect contents QA

### PR DESCRIPTION
**Pull request by hanbyul-here**
Close https://github.com/NASA-IMPACT/veda-config/issues/121

* Left out some items that are currently not over-writable. (ex. delete 'Overview' from the dataset overview page title, Thematic area intro (Welcome to~) )

### CODE REVIEW

**Comment by hanbyul-here** [comment]
@Catalina-Moller this is the docs that have contents: https://docs.google.com/document/d/1HAzCTjPzISjw9tz_G2GftBVTS5Z3S5tm/edit 

I skipped some items that are not configurable (Most of Header, welcome messages on the page).

**Comment by Catalina-Moller** [comment]
@hanbyul-here Perfect! 
I have already sent a request for access to the doc so I can access and view the content.

**Comment by Catalina-Moller** [comment]
@hanbyul-here I have found some observations:
1- According to the document with the changes, in line 94 the words "so far" should also be deleted, not only the words "has been".
image

2- The following paragraph in the GEOGLAM Dataset needs to be changed.

"In the southern side (Indonesia), (delete-the wet-season rice is complete, and the dry-season rice is underway. ) during the wet season, reduced rainfall delayed rice planting and ultimately resulted in less total area planted and reduced yields. As a consequence of the wet season delay, dry season rice planting was delayed. Despite the delay, good rainfall (delete-has) continued in the traditional dry season. " 

3- Is it possible to change the title of the datasets? 
The document with the changes specifies that the title of the dataset "NCEO Africa Aboveground Woody Biomass" should be changed to "National Centre for Earth Observation (NCEO) Biomass Datasets" and the title of the dataset "Monthly Gridded Sea Ice Thickness" to "Sea Ice Thickness Datasets".

**Comment by danielfdsilva** [comment]
@Catalina-Moller Addressed your feedback with the last commit. Let me know if it looks good.

**Comment by Catalina-Moller** [comment]
@danielfdsilva All changes seem to have been made correctly!

**Review by Catalina-Moller — APPROVED** [review]
All changes seem to have been made correctly!

**Pull request merged**
