### PR TITLE
Content: GST CO2

### PR DESCRIPTION
**Pull request by slesaad**
## Adding content
Dataset configuration for GST CO2 budgets

---

## Content checklist

Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/CONTENT.md) for more details.

### Any content
- [x] Cover image with proper attribution (when relevant) is present.
- [x] Cover images do not contain any text (they're used as a background and text may not be readable).
- [x] All images are not too big/heavy. As a general rule of thumb, they should not weigh more than 500KB, or be larger than 2000px. See the [media guide](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/frontmatter/media.md#media) for more info.
- [x] Content was added using the available [MDX Blocks](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/MDX_BLOCKS.md).

### Datasets
- [x] [Layer description](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/frontmatter/layer.md#properties) is defined.
- [x] [Layer legend](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/frontmatter/layer.md#legend) is setup.
- [x] The Dataset is showing up on the map correctly

### Discoveries
- [ ] [Publication date](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/CONTENT.md#discoveries) value is set

### CODE REVIEW

**Comment by aboydnw** [comment]
Looks pretty good to me. @slesaad have you been able to review the color scales with Brendan or Matt?

**Comment by slesaad** [comment]
@aboydnw i've responded to the email thread for them to review the content

**Comment by danielfdsilva** [comment]
@slesaad This content will now have to be updated according to new approach for taxonomies.
See the content [migration guide on the veda-ui release](https://github.com/NASA-IMPACT/veda-ui/releases/tag/v2.0.0).

**Comment by j08lue** [comment]
I updated the taxonomy definitions in a PR against this branch, @slesaad. Merging that should get this PR here in shape for merging, too. 

- https://github.com/NASA-IMPACT/veda-config/pull/307

**Comment by danielfdsilva** [comment]
@j08lue @slesaad I just rebased this on top of develop integrating the changes that Jonas made. This was the diff is smaller, making it easier to review.

**Comment by j08lue** [comment]
Thanks, @danielfdsilva. @slesaad - I'll leave it to you to decide when this is ready for merging from a content perspective. Code-wise, it should be good now.

**Review by j08lue — APPROVED** [review]
LGTM in terms of completeness and configuration. Can't judge content.

**Pull request closed without merging**
