### PR TITLE
Initial push of Camp Fire story.

### PR DESCRIPTION
**Pull request by acblackford**
## Adding content

_Replace with brief description/list of the content being added_

---

## Content checklist

Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/CONTENT.md) for more details.

### Any content
- [ ] Cover image with proper attribution (when relevant) is present.
- [ ] Cover images do not contain any text (they're used as a background and text may not be readable).
- [ ] All images are not too big/heavy. As a general rule of thumb, they should not weigh more than 500KB, or be larger than 2000px. See the [media guide](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/frontmatter/media.md#media) for more info.
- [ ] Content was added using the available [MDX Blocks](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/MDX_BLOCKS.md).

### Datasets
- [ ] [Layer description](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/frontmatter/layer.md#properties) is defined.
- [ ] [Layer legend](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/frontmatter/layer.md#legend) is setup.
- [ ] The Dataset is showing up on the map correctly

### Stories
- [ ] [Publication date](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/CONTENT.md#stories) value is set

### CODE REVIEW

**Review by moradology — APPROVED** [review]
Compelling; looks like everything is here.

**Comment by j08lue** [comment]
@acblackford I hear that this story has been approved for release.

However, the images seem to be too big:

> As a general rule of thumb, they should not weigh more than 500KB, or be larger than 2000px. See the [media guide](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/frontmatter/media.md#media) for more info.

Could you please make them smaller to match the size restrictions?

**Comment by j08lue** [comment]
Thanks @acblackford. I see you made some more changes - please let me know when this is ready for merging.

**Comment by acblackford** [comment]
@j08lue The story is now ready to be merged- pictures have been compressed to fit size restrictions, and hyperlink formatting has been addressed.

**Review by j08lue — APPROVED** [review]
All content seems to be formatted correctly now. Ready for merging, from a technical perspective.

**Pull request merged**
