### PR TITLE
Deploy v0.8.0

### PR DESCRIPTION
**Pull request by danielfdsilva**
# Changelog v0.8.0

## 🎉 Features
- Remove thematic areas content (https://github.com/NASA-IMPACT/veda-ui/issues/494 https://github.com/NASA-IMPACT/veda-ui/issues/509)
- Add some dataset sources based on [sources spreadsheet](https://docs.google.com/spreadsheets/d/1hF74CLrVktNVKfNg9W14uNXcgT2OvzX5q1GEgtru9Ig/edit#gid=0)
- UI: Merge all datasets under data catalog page
- UI: Merge all discoveries under a discoveries hub page
- UI: Add filtering and search options to data catalog and discoveries hub (https://github.com/NASA-IMPACT/veda-ui/issues/511 https://github.com/NASA-IMPACT/veda-ui/issues/512)
- UI: Add sources as a dataset and discovery metadata property
- UI: Create taxonomies for thematic areas and sources (https://github.com/NASA-IMPACT/veda-ui/issues/510)
- UI: Change default vector data color (temporary measure for fire datasets)

## 🚀 Improvements
- UI: File and code cleanup
- UI: Improve date slider performance on large datasets (https://github.com/NASA-IMPACT/veda-ui/issues/504)

## 🐛 Fixes
- 🦗

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@karitotp We're still finalizing some issues and PRs over at veda-ui, but could you start with a some QA testing, to see if there's something popping up?

**Comment by danielfdsilva** [comment]
@karitotp All PRs and issues are now handled

**Comment by karitotp** [comment]
@danielfdsilva, everything works fine! I only noticed this:

> UI: Add filtering and search options to data catalog and discoveries hub

Clicking on the topic pill on the discovery cards should filter the discovery cards as it does in the data catalog cards? Currently, it scrolls up until the bar of filters, but the filter does not occur.

> UI: Change default vector data color (temporary measure for fire datasets)

Could you please point me to the data catalog that have vector data?

**Comment by danielfdsilva** [comment]
@karitotp the discovery pill was fixed! great catch! 🎉
Unfortunately we don't have data for the fire yet. It is being created: https://github.com/NASA-IMPACT/veda-config/pull/234 Not to worry for now

**Review by karitotp — APPROVED** [review]

**Pull request merged**
