### PR TITLE
Update GEOGLAM Crop Conditions layer description

### PR DESCRIPTION
**Pull request by j08lue**
Adding missing layer description.

Text taken from figure caption at https://cropmonitor.org/index.php/about/aboutus/

image

### CODE REVIEW

**Comment by j08lue** [comment]
I verified that all looks as expected in the preview - you can now find the dataset by the "GEOGLAM" source and the updated description is visible in the Exploration.

**Review by hanbyul-here — APPROVED** [review]
lgtm!

**Comment by j08lue** [comment]
How do you handle these content updates, @hanbyul-here - do we merge this already so it gets up on staging or bundle with more updates to make larger releases? 🤷 

Either is fine for me. Just want to make sure this PR does not gather too much dust.

**Comment by hanbyul-here** [comment]
We do not have rigid rules for how the content changes should get deployed since that often depends on the need of stakeholders. Other than the ones that need to go out asap, we usually stack the changes on the staging and release them along with others. We usually check all the PRs merged to the staging and move them to the production release log (like this one: https://github.com/NASA-IMPACT/veda-config/pull/255). That being said, it will help us if you can make the message of pr copy-and-pastable with the full context in the future! We plan to release the UI module next sprint, so this change will likely go out with that change.

**Pull request merged**
