### PR TITLE
Stage v0.12.0

### PR DESCRIPTION
**Pull request by danielfdsilva**
# Changelog v0.12.0

## 🎉 Features
- Update UI module to v2.31 ([Changelog v2.3.0](https://github.com/NASA-IMPACT/veda-ui/releases/tag/v2.3.0), [Changelog v2.3.1](https://github.com/NASA-IMPACT/veda-ui/releases/tag/v2.3.1))
- Content Removal: Agriculture and Biomass discoveries

## 🚀 Improvements
- 🦗 

## 🐛 Fixes
- 🦗

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@karitotp Can you perform a quick QA test to ensure that the changes from veda-ui [v2.2.0](https://github.com/NASA-IMPACT/veda-ui/releases/tag/v2.2.0) and [v2.3.0](https://github.com/NASA-IMPACT/veda-ui/releases/tag/v2.3.0) all perform well?

**Review by j08lue — APPROVED** [review]
Looks good and the visible changes - Feedback button, Access Data button - fit in nicely also with this instance, IMO.

**Comment by karitotp** [comment]
@danielfdsilva, everything looks good and is working well.

The only weird thing I noticed apart from the changes for this version, is that when you click on the source name (above the data title) in the cards, the filters seem to stop working right.

Selection_1004

Selection_1005

**Review by karitotp — APPROVED** [review]

**Comment by j08lue** [comment]
Well spotted, @karitotp, thanks!

**Comment by danielfdsilva** [comment]
@karitotp Great catch. PR up with the fix

**Pull request merged**
