### PR TITLE
Fix issue 451

### PR DESCRIPTION
**Pull request by amarouane-ABDELHAK**
## Why are you creating this Pull Request?

- To fix the issue described [here](https://github.com/NASA-IMPACT/veda-config/issues/451)

### CODE REVIEW

**Comment by amarouane-ABDELHAK** [comment]
@hanbyul-here @anayeaye and I were wondering why we didn't use Domain_PROD as a relative path instead of a hardcoded domain name, if both work. Do you know the reason behind having the Domain_PROD variable as a full URL?

**Comment by hanbyul-here** [comment]
Thanks for working on the fix. The variable is used to specify where the bundled assets are served. 
where it is passed to be used for application base url: (https://github.com/NASA-IMPACT/veda-config/blob/8654ea1a196b37a44841e9a28492c689b8e3ae0c/.github/workflows/deploy-prod.yml#L65) 
The absolute path should work in theory, but I am honestly unsure if I am missing anything and if this change will bring unexpected outcomes. 

As far as I know, we don't have a staging environment for earthdata.nasa.gov to test the URL change. Considering earthdata.nasa.gov has low traffic, should we just test on the production? or do you have any idea how we can test this change to not introduce any unexpected outcome without deploying it to production?

**Comment by amarouane-ABDELHAK** [comment]
I have build it locally with PUBLIC_URL as a path instead of URL and did not notice any side effect

**Review by hanbyul-here — APPROVED** [review]
thanks for working on it

**Pull request merged**
