### PR TITLE
Content: fire

### PR DESCRIPTION
**Pull request by mccabete**
## Adding content

FEDS fire Perimeter description, with links to datasets based on FEDS fire perimeters. This is a first draft, that hasn't yet had feedback from wider EIS fire team. I will want to update the initial image, and will have more/different content. This should start a good group conversation though.

### Any content
- [x] Cover image with proper attribution (when relevant) is present.
- [x] Cover images do not contain any text (they're used as a background and text may not be readable).
- [x] All images are not too big/heavy. As a general rule of thumb, they should not weigh more than 500KB, or be larger than 2000px. See the [media guide](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/frontmatter/media.md#media) for more info.
- [x] Content was added using the available [MDX Blocks](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/MDX_BLOCKS.md).

### Datasets
- [ ] [Layer description](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/frontmatter/layer.md#properties) is defined.
- [ ] [Layer legend](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/frontmatter/layer.md#legend) is setup.
- [ ] The Dataset is showing up on the map correctly

### CODE REVIEW

**Review by danielfdsilva — COMMENTED** [review]
@mccabete Looks good overall. Perhaps the map layer description could be improved. I imagine it could be the same as the dataset?

**Comment by mccabete** [comment]
@danielfdsilva  -- that's a great point. Could you point me to where I would edit that? For some reason I assumed that I could n't edit that section.

**Comment by danielfdsilva** [comment]
@mccabete Anything we can help with to get this merged?

**Comment by mccabete** [comment]
Hey, sorry to be holding this up! I'm OoO untill Monday. If you are ok with me making changes on the merged branch, then I am fine with it getting merged before my edits.

________________________________

**Comment by j08lue** [comment]
@danielfdsilva or @hanbyul-here, can you judge what is left to do on this PR before it can be merged?

**Pull request merged**
