### PR TITLE
NOT READY FOR MERGE: Add CYGNSS L3 for Demo

### PR DESCRIPTION
**Pull request by freitagb**
## Why are you creating this Pull Request?

- [Adding Datasets or Stories](?title=Content%3A%20%3Cname%3E&expand=1&template=content.md)
This PR is a demo for integrating CYGNSS level-3 data products into the VEDA dashboard

### CODE REVIEW

**Comment by freitagb** [comment]
@hanbyul-here @j08lue - how easy was it to merge the new A&E environment for the HD-nightlights preview. Is it easy enough to make that available here as well?

**Comment by hanbyul-here** [comment]
@brianmfreitag, I have activated the new A&E page for this branch. 

To enable the new A&E, you will need to add a single line to the .env file once the dashboard successfully updates the UI module to version 4.0 !  (https://github.com/NASA-IMPACT/veda-ui/tree/main/app/scripts/components/exploration)

**Comment by freitagb** [comment]
Oh great! Thanks! I didn't realize you set the .env for me. I appreciate the quick turnaround @hanbyul-here

**Comment by freitagb** [comment]
No longer needed.

**Pull request closed without merging**
