### PR TITLE
Update CI scripts

### PR DESCRIPTION
**Pull request by danielfdsilva**
Based on @slesaad's work on https://github.com/NASA-IMPACT/veda-config-ghg/pull/11 update the CI script

The staging deploy was removed since it was not working and the staging env is handled by netlify at https://visex.netlify.app/

### CODE REVIEW

**Comment by slesaad** [comment]
this might be an opportunity to use OIDC instead of long-lived keys 🤔

**Comment by danielfdsilva** [comment]
@slesaad definitely! feel free to make the change

**Comment by slesaad** [comment]
@danielfdsilva I created a PR against this branch with the updates for OIDC; https://github.com/NASA-IMPACT/veda-config/pull/292
Please review that. Once that's merged, this should be good to go!

**Comment by danielfdsilva** [comment]
@slesaad back to you to approve this one so we can merge!

**Review by slesaad — APPROVED** [review]
Looks good to me!

**Pull request merged**
