### PR TITLE
Update UI to v5.11.3

### PR DESCRIPTION
**Pull request by hanbyul-here**
### Updating VEDA-UI
- [x] Confirmed that [updating the `veda-ui` submodule](https://github.com/NASA-IMPACT/veda-config/blob/main/docs/DEVELOPMENT.md#development) is needed.
- [x] Ensured that the correct version of veda-ui is being used
- [x] Reviewed the veda-ui changelogs for relevant updates
- [x] Tested that the changes work as expected with the current instance configuration

### CODE REVIEW

**Review by sandrahoang686 — APPROVED** [review]
git commit hash matches, validated the things in v5.11.3 in changelog in deploy preview, lgtm

**Comment by aboydnw** [comment]
I see some issues with the [new story](https://deploy-preview-500--visex.netlify.app/stories/2024-tornadoes), a few of the map blocks show the error message below. I don't see the same issue in the [netlify preview from the original PR](https://deploy-preview-420--visex.netlify.app/stories/2024-tornadoes). any ideas?
image

**Comment by hanbyul-here** [comment]
@aboydnw It seems the original preview url has an outdated UI version. If you look at staging now, the map breaks there too. https://visex.netlify.app/stories/2024-tornadoes I think we should just fix mdx file.

**Review by aboydnw — APPROVED** [review]
Looks good now 👍

**Pull request merged**
